# Generated by Django 4.2.1 on 2023-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_name_reading', models.CharField(max_length=100)),
                ('song_auther', models.CharField(max_length=100)),
                ('song_catname', models.CharField(max_length=20)),
                ('song_bpm', models.IntegerField()),
                ('song_release', models.DateField()),
                ('expert_const', models.DecimalField(decimal_places=1, max_digits=4)),
                ('expert_notes', models.IntegerField()),
                ('master_const', models.DecimalField(decimal_places=1, max_digits=4)),
                ('master_notes', models.IntegerField()),
                ('ultima_const', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ultima_notes', models.IntegerField()),
                ('is_const_unknown', models.BooleanField()),
            ],
        ),
    ]
